apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-service-staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: greeter-service
      environment: staging
  template:
    metadata:
      labels:
        app: greeter-service
        environment: staging
    spec:
      containers:
        - image: willjschmitt/greeter-server@sha256:d7e44c9827a72d54a14a31d442ba2ef4ed8b1df707cde602e0fd66f4fc09caec
          imagePullPolicy: IfNotPresent
          name: greeter-server
          ports:
            - containerPort: 5000
